import { useState } from 'react';
import ProjectCard from '../components/ProjectCard';
import { projects } from '../projects';
const categories = ['All projects', 'Full-stack', 'AI engineering', 'Mobile'];
export default function Self() {
 const [filter, setFilter] = useState('All projects');
 const visible = projects.filter(p => filter === 'All projects' || p.category === filter);
 return <section className="page-content"><p className="eyebrow">THE PLAYGROUND / PERSONAL PROJECTS</p><h1 className="page-title">Curiosity, <em>in production.</em></h1><p className="page-intro">A collection of things I’ve built to explore what’s possible. From secure backends to local AI, each one starts with a question.</p><div className="filter-bar" aria-label="Filter projects">{categories.map(category => <button key={category} onClick={() => setFilter(category)} aria-pressed={filter === category}>{category}<span>{category === 'All projects' ? projects.length : projects.filter(p => p.category === category).length}</span></button>)}</div><p className="sr-only" role="status">Showing {visible.length} projects</p><div className="projects-grid">{visible.map(project => <ProjectCard key={project.id} project={project} index={projects.indexOf(project)}/>)}</div><section className="toolbox section-block"><p className="eyebrow">MY EVERYDAY TOOLKIT</p><h2>The tools behind <em>the work.</em></h2><div className="toolbox-grid">{[['Languages', 'Java, TypeScript, JavaScript, Python, SQL'], ['Frameworks', 'Spring Boot, React, FastAPI, React Native'], ['Infrastructure', 'Docker, Kubernetes, Jenkins, GitHub Actions'], ['AI engineering', 'LangChain, ChromaDB, Ollama, OpenAI'], ['Quality', 'JUnit, Mockito, Jest, Cypress, SonarQube'], ['Data & workflows', 'PostgreSQL, Redis, RabbitMQ, Apache Airflow']].map(([title, text]) => <div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></section></section>;
}
